services:
  mongodb:
    image: mongo:latest
    container_name: ticktick-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: mongod --auth --quiet --logpath /dev/null
    logging:
      driver: "none"
    networks:
      - ticktick-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    build: .
    container_name: ticktick-app
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs:delegated
      - ./:/app:cached
    networks:
      - ticktick-network
    healthcheck:
      test: ["CMD", "python", "-c", "import pymongo; pymongo.MongoClient('mongodb://admin:password@mongodb:27017/').admin.command('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local

networks:
  ticktick-network:
    driver: bridge 