services:
  mongodb:
    image: mongo:latest
    container_name: ticktick-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: mongod --auth --quiet
    networks:
      - ticktick-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    build: .
    container_name: ticktick-app
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:delegated
      - ./:/app:cached
      - ./prompts:/app/prompts:cached
    networks:
      - ticktick-network
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  mongodb_data:
    driver: local

networks:
  ticktick-network:
    driver: bridge 